---
- name: 배포판 별로 웹서버 설치
  hosts: all
  become: true
  gather_facts: true
  vars:
    dist_name: "{{ 'ubuntu' if ansible_distribution == 'Ubuntu'
                   else 'amazon' }}"

  tasks:
    - name: "에서의 작업"
      include_tasks: "{{ dist_name }}.yml"

    - name: hostname 출력
      debug:
        msg:
         - "Hostname : {{ ansible_hostname }}"
         - "eth0 : {{ ansible_eth0.ipv4.address }}"

