---
- name: 배포판 별로 웹서버 설치
  hosts: all
  become: true
  gather_facts: true
  


  tasks:
    - name: amazon 에서의 작업
      include_tasks: amazon.yml
      when: ansible_distribution == 'Amazon'

    - name: ubuntu 에서의 작업
      include_tasks: ubuntu.yml
      when: ansible_distribution == 'Ubuntu'

